name: Cypress Tests

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  cypress-run:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    
    # We provision MongoDB as a service for the backend to run on
    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
          
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'

    - name: Install Frontend Dependencies
      run: npm ci
      working-directory: ./frontend
      
    - name: Install Backend Dependencies
      run: npm ci
      working-directory: ./backend

    - name: Start Backend background
      run: npm run dev &
      working-directory: ./backend
      env:
        MONGO_URI: mongodb://localhost:27017/secure-hunt-test
        PORT: 5001
        JWT_SECRET: testing-secret

    - name: Cypress run (Firefox)
      uses: cypress-io/github-action@v6
      with:
        browser: firefox
        working-directory: ./frontend
        start: npm run dev
        wait-on: 'http://localhost:5001, http://localhost:5173'
      env:
        # Pass necessary variables for Cypress or Vite
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
